server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mahasiswa_db
    username: postgres
    password: aamaulana10
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    port: 6379
  cache:
      type: redis
      ttl:

app:
  redis-ttl-in-second: 60

#logging:
#  level:
#    org.springframework.cache: DEBUG
#    org.springframework.data.redis: DEBUG
#    org.springframework.data.redis.serializer: TRACE
#    org.springframework.web: TRACE
#  console:
#    level: TRACE